# Practice Activity 6.2: Iteration

Completed solutions for all eight exercises. Run the cells from top to bottom.

The check-ins referenced in the supplied activity are available in the [course textbook's Iteration chapter](https://ds-ml-with-python.github.io/Course-Textbook/06-iteration.html). The current chapter headings have shifted, but the exercise text is preserved below. The song examples use the chapter's `range(100, 97, -1)`, which produces 100, 99, and 98.

1.  Complete the Check-in before Section 7.2.1:

    Modify the code above so that instead of creating one long string, we create a list, where each element is one of the verses of the song.

In [1]:
def sing_verse(num):
    """Return one verse about bottles of beer as a string."""
    return (
        f"{num} bottles of beer on the wall\n"
        f"{num} bottles of beer\n"
        "Take one down, pass it around,\n"
        f"{num - 1} bottles of beer on the wall\n"
    )


song = []
for num in range(100, 97, -1):
    song.append(sing_verse(num))

# Each list element contains one complete verse.
assert len(song) == 3
assert song[0].startswith("100 bottles of beer")
assert song[-1].endswith("97 bottles of beer on the wall\n")
song

['100 bottles of beer on the wall\n100 bottles of beer\nTake one down, pass it around,\n99 bottles of beer on the wall\n',
 '99 bottles of beer on the wall\n99 bottles of beer\nTake one down, pass it around,\n98 bottles of beer on the wall\n',
 '98 bottles of beer on the wall\n98 bottles of beer\nTake one down, pass it around,\n97 bottles of beer on the wall\n']

The accumulator starts as an empty list. `append()` adds the entire string returned by `sing_verse()` as one element, so `song` contains three verse strings rather than one combined string.

2.  Complete the first bullet of the Check-in before Section 7.3.

    Write a function `sqrt_pos_unvec()` that takes in a single value as an argument, and returns the square root if the value is positive. Then, write a for loop that uses this function to construct a new vector where the positive values are square rooted.

In [2]:
import numpy as np


def sqrt_pos_unvec(value):
    """Square-root a positive scalar; leave zero and negatives unchanged."""
    if value > 0:
        return np.sqrt(value)
    return value


a_vec = np.array([-2, 1, -3, -9, 7])
rooted_values = []
for value in a_vec:
    rooted_values.append(sqrt_pos_unvec(value))

sqrt_loop = np.array(rooted_values, dtype=float)

assert sqrt_pos_unvec(0) == 0
assert sqrt_pos_unvec(-4) == -4
np.testing.assert_allclose(sqrt_loop, [-2, 1, -3, -9, np.sqrt(7)])
sqrt_loop

array([-2.        ,  1.        , -3.        , -9.        ,  2.64575131])

The function handles one value at a time. The loop collects each returned value in a new vector. Nonpositive values remain unchanged, and 7 becomes approximately 2.645751 rather than an integer.

3.  Complete the second bullet of the Check-in before Section 7.3.

    Write a function `sqrt_pos_vec()` that takes in a vector of values, and returns a vector with the positive values square rooted. Do not use a for loop inside your function.

In [3]:
def sqrt_pos_vec(values):
    """Return a new float array, square-rooting only its positive entries."""
    result = np.asarray(values, dtype=float).copy()
    is_positive = result > 0
    result[is_positive] = np.sqrt(result[is_positive])
    return result


sqrt_vectorized = sqrt_pos_vec(a_vec)

np.testing.assert_allclose(sqrt_vectorized, sqrt_loop)
np.testing.assert_array_equal(a_vec, [-2, 1, -3, -9, 7])
np.testing.assert_allclose(sqrt_pos_vec([0, -4, 4, 2.25]), [0, -4, 2, 1.5])
sqrt_vectorized

array([-2.        ,  1.        , -3.        , -9.        ,  2.64575131])

A boolean mask selects only positive entries. Converting to a floating-point copy preserves fractional square roots and keeps the original vector unchanged. Taking the square root only on the selected entries also avoids evaluating square roots of negative numbers.

4.  Complete the Check-in before Section 7.4.
    - a. Write a `sing_verse_3()` function that also lets us change the container (e.g. bottle, can, …) at each step of the loop.
    - b. Use `map()` to sing a few verses.
    - c. What happens if you supply three different drinks, but only two different types of containers?

In [4]:
def sing_verse_3(num, drink, container):
    """Return a verse with a chosen drink and plural container name."""
    return (
        f"{num} {container} of {drink} on the wall\n"
        f"{num} {container} of {drink}\n"
        "Take one down, pass it around,\n"
        f"{num - 1} {container} of {drink} on the wall\n"
    )


nums = range(100, 97, -1)
drinks = ["beer", "milk", "lemonade"]
containers = ["bottles", "cans", "glasses"]

# Parts a and b: map one number, drink, and container into each verse.
mapped_song = list(map(sing_verse_3, nums, drinks, containers))
assert len(mapped_song) == 3
print("Three drinks and three containers:\n")
print("\n".join(mapped_song))

# Part c: map stops when the shortest iterable runs out.
short_containers = ["bottles", "cans"]
short_song = list(map(sing_verse_3, nums, drinks, short_containers))
assert len(short_song) == 2
assert "lemonade" not in "".join(short_song)
print("Three drinks and two containers:\n")
print("\n".join(short_song))

Three drinks and three containers:

100 bottles of beer on the wall
100 bottles of beer
Take one down, pass it around,
99 bottles of beer on the wall

99 cans of milk on the wall
99 cans of milk
Take one down, pass it around,
98 cans of milk on the wall

98 glasses of lemonade on the wall
98 glasses of lemonade
Take one down, pass it around,
97 glasses of lemonade on the wall

Three drinks and two containers:

100 bottles of beer on the wall
100 bottles of beer
Take one down, pass it around,
99 bottles of beer on the wall

99 cans of milk on the wall
99 cans of milk
Take one down, pass it around,
98 cans of milk on the wall

**Part c:** `map()` stops when its shortest input iterable is exhausted. Three drinks with two containers therefore produce two verses. The third drink and number are unused; Python does not raise an error or reuse the last container. Here, the paired verses use beer in bottles and milk in cans. Container names are supplied in their plural form because the demonstrated counts are all greater than one.

5.  Complete the Check-in before Section 7.5.

    Use a lambda function with `sing_verse_3()` to sing a few verses about milk in glasses.

In [5]:
milk_song = list(
    map(lambda num: sing_verse_3(num, "milk", "glasses"), range(100, 97, -1))
)

assert len(milk_song) == 3
assert milk_song[0].startswith("100 glasses of milk")
assert milk_song[-1].endswith("97 glasses of milk on the wall\n")
print("\n".join(milk_song))

100 glasses of milk on the wall
100 glasses of milk
Take one down, pass it around,
99 glasses of milk on the wall

99 glasses of milk on the wall
99 glasses of milk
Take one down, pass it around,
98 glasses of milk on the wall

98 glasses of milk on the wall
98 glasses of milk
Take one down, pass it around,
97 glasses of milk on the wall

The lambda varies the number while supplying the same drink (`"milk"`) and container (`"glasses"`) to every call of `sing_verse_3()`. Converting the map object to a list saves the three verses.

6. Load the `penguins` dataset from the `palmerpenguins` library, as well as any other libraries you need. Then write a function that takes in information about a penguin, and returns one of the following definitions:

*   "Big Mouth Billy": Male penguins with bill length times bill depth greater than 800.
*   "Dainty Daisy": Female penguins with flipper length less than 5% of body mass.
*   "Average Adelie:" Any Adelie penguins that do not fall into either category.
*   "Other": Any penguins that do not fall into any of the categories.

In [6]:
import pandas as pd
from palmerpenguins import load_penguins

penguins = load_penguins()


def category_penguin(penguin):
    """Classify one penguin row using the conditions in the stated order."""
    sex = penguin.get("sex")
    species = penguin.get("species")
    bill_length = penguin.get("bill_length_mm")
    bill_depth = penguin.get("bill_depth_mm")
    flipper_length = penguin.get("flipper_length_mm")
    body_mass = penguin.get("body_mass_g")

    if (
        pd.notna(sex)
        and sex == "male"
        and pd.notna(bill_length)
        and pd.notna(bill_depth)
        and bill_length * bill_depth > 800
    ):
        return "Big Mouth Billy"
    if (
        pd.notna(sex)
        and sex == "female"
        and pd.notna(flipper_length)
        and pd.notna(body_mass)
        and flipper_length < 0.05 * body_mass
    ):
        return "Dainty Daisy"
    if pd.notna(species) and species == "Adelie":
        return "Average Adelie:"
    return "Other"


# Check every label, the strict inequality boundaries, and missing data.
assert category_penguin({
    "species": "Gentoo", "sex": "male",
    "bill_length_mm": 45, "bill_depth_mm": 18,
}) == "Big Mouth Billy"
assert category_penguin({
    "species": "Gentoo", "sex": "female",
    "flipper_length_mm": 199, "body_mass_g": 4000,
}) == "Dainty Daisy"
assert category_penguin({
    "species": "Adelie", "sex": "male",
    "bill_length_mm": 40, "bill_depth_mm": 20,
}) == "Average Adelie:"  # Exactly 800 is not greater than 800.
assert category_penguin({
    "species": "Gentoo", "sex": "female",
    "flipper_length_mm": 200, "body_mass_g": 4000,
}) == "Other"  # Equality is not less than 5% of body mass.
assert category_penguin({
    "species": "Adelie", "sex": "male",
    "bill_length_mm": np.nan, "bill_depth_mm": 18,
}) == "Average Adelie:"
assert category_penguin({
    "species": "Gentoo", "sex": "female",
    "flipper_length_mm": pd.NA, "body_mass_g": 4000,
}) == "Other"
assert category_penguin({
    "species": "Gentoo", "sex": pd.NA,
    "bill_length_mm": 50, "bill_depth_mm": 20,
}) == "Other"

print(f"Loaded {len(penguins)} penguins with {len(penguins.columns)} variables.")
penguins.head()

Loaded 344 penguins with 8 variables.

/Users/nick_ramel/Downloads/msbawork/.pa6-venv/lib/python3.14/site-packages/palmerpenguins/penguins.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

The rules are checked in their listed order, so an Adelie that qualifies for one of the first two categories receives that category. Missing sex or measurements cannot satisfy a rule that requires them; an Adelie with insufficient measurements can still receive the Adelie fallback, and a remaining penguin receives `"Other"`. This keeps every record in the dataset. The category value `"Average Adelie:"` includes the trailing colon exactly as quoted in the supplied prompt. The 5% rule uses the supplied numeric values in millimeters and grams exactly as requested.

7. Use an iterable function to create a new variable in the data frame called `category_name` that adds these labels.

In [7]:
# axis=1 applies the function to each row rather than each column.
penguins["category_name"] = penguins.apply(category_penguin, axis=1)

assert len(penguins) == 344
assert penguins["category_name"].notna().all()
assert set(penguins["category_name"].unique()) == {
    "Big Mouth Billy", "Dainty Daisy", "Average Adelie:", "Other"
}

penguins.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,category_name
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,Average Adelie:
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,Dainty Daisy
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,Average Adelie:
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,Average Adelie:
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,Average Adelie:
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007,Big Mouth Billy
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007,Dainty Daisy
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007,Average Adelie:
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007,Average Adelie:
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007,Average Adelie:

`DataFrame.apply(..., axis=1)` iterates over the penguin rows and stores one label per row in `category_name`. No rows are removed, including those with missing information.

8. Summarize the `category_name` variable to find the counts for each type.

In [8]:
category_order = ["Big Mouth Billy", "Dainty Daisy", "Average Adelie:", "Other"]
category_counts = (
    penguins["category_name"]
    .value_counts()
    .reindex(category_order, fill_value=0)
    .rename_axis("category_name")
    .reset_index(name="count")
)

assert category_counts["count"].sum() == len(penguins) == 344
category_counts

     category_name  count
0  Big Mouth Billy     71
1     Dainty Daisy     62
2  Average Adelie:    127
3            Other     84

`value_counts()` counts the labels. Reindexing presents all four categories in the order used in the assignment, including a zero count if a category were absent. The counts sum to all 344 penguins.